import type { Metadata } from "next";
import Navbar from '@/components/Navbar/Navbar';
import { Inter } from "next/font/google";
import "../app/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OnEntrée",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full overflow-hidden`}>
        <div className="h-full overflow-y-auto custom-scrollbar">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}